version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: fluxio-postgres
    environment:
      POSTGRES_USER: ${FLUXIO_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${FLUXIO_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${FLUXIO_DB_NAME:-fluxio}
    ports:
      - "${FLUXIO_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: fluxio-postgres-data
